services:
  nodered-app:
    container_name: nodered-app
    image: nodered/node-red:latest-22
    volumes:
      - ./data:/data
      - ./settings.js:/data/settings.js
    environment:
      TZ: "America/Sao_Paulo"
    links:
      - postgres-db
    depends_on:
      - postgres-db
    ports:
      - 1880:1880

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: nodered
      POSTGRES_USER: nodered
      POSTGRES_PASSWORD: "@nodered"
      TZ: "America/Sao_Paulo"
      PGTZ: "America/Sao_Paulo"
    ports:
      - "5434:5434"

  adminer-app:
    image: adminer:latest
    container_name: adminer-app
    depends_on:
      - postgres-db
    ports:
      - "8082:8082"
